ssas

diff --git a/.github/workflows/auto-write-readme.yaml b/.github/workflows/auto-write-readme.yaml
--- a/.github/workflows/auto-write-readme.yaml
+++ b/.github/workflows/auto-write-readme.yaml
@@ -13,7 +13,7 @@ jobs:
 
     steps:
       - name: Checkout repository
-        uses: actions/checkout@v2
+        uses: actions/checkout@v4
 
       - name: Set environment variables for testing
         run: |
@@ -26,20 +26,23 @@ jobs:
           name_env="${{ env.name_env }}"
           date_env="${{ env.date_env }}"
 
-          NEW_ROW="| ${NAME} | ${DATE} |"
-          echo "NEW_ROW=$NEW_ROW" 
+          # Create the new row to add to the table
+          new_row="| $name_env | $date_env |"
 
-          # Read the README into a variable
-          README=$(cat README.md)
+          # Read the existing README.md file
+          readme_content=$(cat README.md)
 
-          # Find the position of the table end
-          TABLE_END_POS=$(echo "$README" | grep -n -o -e "$TABLE_END" | cut -d ':' -f 1)
+          # Check for table header existence
+          if ! grep -qE "^\| name \| date \|" README.md; then
+            echo "Table header not found. Exiting workflow."
+            exit 1
+          fi
 
-          # Insert the new row before the table end
-          README=$(echo "$README" | sed "${TABLE_END_POS}i${NEW_ROW}")
+          # Insert the new row after the table header and ensure proper formatting
+          updated_readme=$(echo "$readme_content" | awk -v new_row="$new_row" 'BEGIN {found=0} {print} /^\| name \| date \|/ {getline; print; if (!found) {print new_row; found=1}}')
 
-          # Overwrite the README file
-          echo "$README" > README.md
+          # Overwrite the README.md file with the updated content
+          echo "$updated_readme" > README.md
 
       - name: Commit and push changes
         run: |
